from cesnet_tszoo.configs.series_based_config import SeriesBasedConfig
from cesnet_tszoo.configs.time_based_config import TimeBasedConfig
from cesnet_tszoo.configs.combined_config import CombinedConfig
